name: Approve and Unblock PR

on:
  issue_comment:
    types: [created] # Triggered when a comment is added
  pull_request_review:
    types: [submitted] # Triggered when a review is submitted

jobs:
  unblock_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Trigger Source
        id: check_trigger
        run: |
          echo "Checking trigger source..."
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" =~ "looks good to me!" ]]; then
              echo "approved=true" >> $GITHUB_ENV
            else
              echo "approved=false" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            if [[ "${{ github.event.review.state }}" == "approved" ]]; then
              echo "approved=true" >> $GITHUB_ENV
            else
              echo "approved=false" >> $GITHUB_ENV
            fi
          else
            echo "approved=false" >> $GITHUB_ENV
          fi
      
      - name: Unblock PR if Approved
        if: ${{ env.approved == 'true' }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Unblocking pull request..."
            if [ "${{ github.event.issue.number }}" != "" ]; then
              PR_NUMBER=${{ github.event.issue.number }}
            elif [ "${{ github.event.pull_request.number }}" != "" ]; then
              PR_NUMBER=${{ github.event.pull_request.number }}
            else
              echo "Error: Unable to determine pull request number."
              exit 1
            fi
        
            curl -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels/block
      